id: ICCC61061
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:09:54+00:00'
last_modified: '2022-06-07T13:48:37.867125+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18640
  title: རྒྱ་བོད་ཤན་སྦྱར་གྱི་སྐྱེ་དངོས་རིག་པའི་ཚིག་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    EC32:
      image_group_id: I8LS18642
      title: ''
      total_pages: 259
      order: 1
      base_file: EC32.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
